[workspace]
resolver= "2"

members = ["orchestrator", "embedcore", "cyber-bevy"]

# [profile.release]
# strip = false   # symbols are not flashed to the microcontroller, so don't strip them.
# lto = true
# opt-level = "z" # Optimize for size.
# #incremental = false
# codegen-units = 1
