name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install avr-libc gcc-avr pkg-config avrdude libudev-dev build-essential 
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-12-28
          components: rust-src
      - name: Build documentation (workspace)
        run: cargo doc --all-features --no-deps
      - name: Build documentation (Arduino)
        run: cd arduino/ && cargo doc --no-deps && cd ..
      - name: Move arduino doc to common folder
        run: mv  arduino/target/avr-atmega328p/doc/arduino/ ./target/doc
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          publish_branch: gh-pages
          force_orphan: true